"""empty message

Revision ID: 0277956e9a16
Revises: 
Create Date: 2020-12-17 16:18:35.157513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0277956e9a16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bairros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('privilegios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_type')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('nascimento', sa.String(length=20), nullable=True),
    sa.Column('cor', sa.String(length=10), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('rua', sa.String(length=100), nullable=True),
    sa.Column('numero_casa', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('bairro', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bairro'], ['bairros.id'], ),
    sa.ForeignKeyConstraint(['user_type'], ['privilegios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('form_socioeconomico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_rep_familia', sa.String(length=100), nullable=False),
    sa.Column('pessoa', sa.Integer(), nullable=False),
    sa.Column('qtd_pessoas_familia', sa.Integer(), nullable=False),
    sa.Column('qtd_criancas', sa.Integer(), nullable=False),
    sa.Column('gestante', sa.Boolean(), nullable=False),
    sa.Column('qtd_amamentando', sa.Integer(), nullable=False),
    sa.Column('qtd_criancas_deficiencia', sa.Integer(), nullable=False),
    sa.Column('preenchido', sa.Boolean(), nullable=False),
    sa.Column('pessoa_amamenta', sa.Boolean(), nullable=False),
    sa.Column('qtd_gestantes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=400), nullable=False),
    sa.Column('texto', sa.String(length=400), nullable=False),
    sa.Column('criador', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.Column('selo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['criador'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=400), nullable=False),
    sa.Column('criador', sa.Integer(), nullable=False),
    sa.Column('postagem', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criador'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['postagem'], ['postagens.id'], ),
    sa.ForeignKeyConstraint(['resposta'], ['comentarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    op.drop_table('postagens')
    op.drop_table('form_socioeconomico')
    op.drop_table('usuarios')
    op.drop_table('privilegios')
    op.drop_table('categorias')
    op.drop_table('bairros')
    # ### end Alembic commands ###
